### ISSUE TITLE
Pesterchum would not delete and maybe virus.

### ISSUE THREAD

**Issue by lilpaladin1** [illuminatedwax/pesterchum#180]
Pesterchum did not work so I tried deleting it and it would not delete. It said access denied. I even tried using command prompt with admin and it would not delete. I was only able to delete it because AVG saw it as a virus and I deleted it. Is there anyway where I can use it and it not being a virus? If you were wondering it was not running.

**Comment by arcaneAgilmente** [comment]
The program uninstalls just fine through the "Add/Remove program" window.
It is also not a virus. AVG often has a tendency to flag things incorrectly.
