### ISSUE TITLE
program failed to launch

### ISSUE THREAD

**Issue by tvaz** [illuminatedwax/pesterchum#21]
i encountered a problem where launching the application wouldn't do anything. after reinstalling 3 times to no avail, i found on the application's page where it stored its user data and sure enough, deleting it (it remained after uninstalling) and clean installing the program it launched again. thought this was weird (not sure why it happened) so I figured I'd share in case anyone else was able to solve this bug by deleting their user data.

**Comment by ghost** [comment]
I'm having the same issue in a way, my brother got to my computer and wiped my main account and now it wont open at all i've tried installing it again and such but it wont work. i've also deleted the data, or at least the bits i could find. can you help me?

**Comment by sacriesr** [comment]
"i found on the application's page where it stored its user data and sure enough, deleting it" WHAT DOES THIS MEAN

**Comment by tvaz** [comment]
How I fixed this, on windows 7, is by finding the (hidden) folder C:/Users/[your user name]/AppData/Local/Pesterchum, and deleting it. This resets all of your user data (quirks, tags, etc.)

**Comment by ghost** [comment]
I get that deleting your info will work, but is there any easy fix to this where we don't have to delete our stuff?
