### ISSUE TITLE
Pesterchum won't connect consistently (10060)

### ISSUE THREAD

**Issue by tlsctf2** [illuminatedwax/pesterchum#255]
the first time I installed Pesterchum, it didn't connect at all. after that, I reinstalled it a few times (around three, I think) and finally got it working. I closed it by accident a while ago and it won't reconnect now. I don't want to have to uninstall it again but I think my issue could be linked to the "Set as default" box being checked once I made my account

**Comment by tlsctf2** [comment]
I found a way around this. if I click the little notification icon, it seems to open just fine. while the workaround is a good thing, I don't want to have to use it.

**Comment by tlsctf2** [comment]
this doesn't work anymore either. I don't want to have to uninstall again, but it's starting to seem like I have to

**Comment by illuminatedwax** [comment]
By the way the system recently got hung up by something. I've restarted the
servers.
