### ISSUE TITLE
Pesterchum fails to open [Linux]

### ISSUE THREAD

**Issue by ecini** [illuminatedwax/pesterchum#39]
$ pesterchum
Traceback (most recent call last):
  File "pesterchum.py", line 12, in <module>
    import ostools
  File "/home/evan/.pesterchum/ostools.py", line 3, in <module>
    from PyQt4.QtGui import QDesktopServices
ImportError: No module named PyQt4.QtGui

Installed via easyInstaller. If I run from the pesterchunm command, I get this error. Even when I run it by the folder [$ ./pesterchum], I get the same error.
I'm running Fedora 17, 32 bit. I have Python installed.
$ python --version
Python 2.7.3

Any help?

**Comment by illuminatedwax** [comment]
You need to have PyQt4.6 installed.

**Comment by ecini** [comment]
Is there a download link I could have? I can't seem to find an older version on their site. I have the newest version installed, though.

**Comment by illuminatedwax** [comment]
The newest version should work. Try importing the library directly in the python interpreter and see if it works. Maybe your lib is misconfigured.

**Comment by ecini** [comment]
**\* import PyQt4.QtGui
Enters fine without errors
$ pesterchum still errors out :/
I'm pretty new to python, so if i'm doing something wrong, please tell me
