### ISSUE TITLE
I'm getting "IOError: [Errno 2]"

### ISSUE THREAD

**Issue by Generalpie** [illuminatedwax/pesterchum#4]
after unziping the package, i found the absence of logs/chums.js. I only found this out when running the "./pesterchum", and this was echo'd:
Traceback (most recent call last):
  File "pesterchum.py", line 2196, in <module>
    pesterchum = MainProgram()
  File "pesterchum.py", line 2001, in **init**
    self.widget = PesterWindow()
  File "pesterchum.py", line 969, in **init**
    self.chumdb = PesterProfileDB()
  File "pesterchum.py", line 129, in **init**
    fp = open("%s/chums.js" % (self.logpath), 'w')
IOError: [Errno 2] No such file or directory: 'logs/chums.js'

**Comment by Generalpie** [comment]
I forgot to put that this is the 3.14.1 src for linux. my python is up to date

**Comment by kiooeht** [comment]
Looks like it tries to open the 'logs/chums.js' file, and if the file doesn't exist, tries to create it.
However you don't have a 'logs' directory for 'logs/chums.js' to be created in.
That can easily be fixed for the next update, for now just create a 'logs' directory
