### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by headacheugh** [illuminatedwax/pesterchum#5]
After I install the Pesterchum 3.14.1 file and then the folder in C:Pesterchum, my computer tells me that the "application configuration is incorrect" and that I should reinstall it to fix the problem. But I've done that already numerous times, and I still get the same message, so I'm really not sure what to do here! I'm operating on Windows XP.

**Comment by kiooeht** [comment]
Others with the same problem have fixed it by installing this: http://www.microsoft.com/downloads/en/details.aspx?FamilyID=a5c84275-3b97-4ab7-a40d-3802b2af5fc2

**Comment by headacheugh** [comment]
Okay, awesome, that worked! Thanks!
