### ISSUE TITLE
It won't open?

### ISSUE THREAD

**Issue by spacianMinecrafter** [illuminatedwax/pesterchum#61]
I've tried using the debug log, but it won't run at ALL. It loads, then stops. I've checked Task Manager; it doesn't even show it attempting to load. 
Pesterchum itself won't load either, which is why I've been trying the debugging. 

I've also uninstalled and reinstalled about three times now. Still nothing.
Any suggestions?

**Comment by illuminatedwax** [comment]
The debug log should output a "debug.log" file that contains the debugging
information. Is the file empty/non-existent?

**Comment by spacianMinecrafter** [comment]
I got pesterchum_debug and pesterchum_debug.exe.manifest when I downloaded
the debug log. I believe the file is nonexistant.

**Comment by spacianMinecrafter** [comment]
Nevermind- I just found it. Thanks!

**Comment by spacianMinecrafter** [comment]
Now, the question is how do I encounter the Pesterchum problem? Because if it won't load, I can't exactly do so.

**Comment by illuminatedwax** [comment]
How are you running it? Did you put the debug exe file in the same
directory? If you try to run it and it closes down immediately, that sounds
like it's running but immediately finding some kind of error. The debug
program should be able to catch what this is.

On Thu, Jan 10, 2013 at 10:51 PM, spacianMinecrafter <
notifications@github.com> wrote:

> Now, the question is how do I encounter the Pesterchum problem? Because if
> it won't load, I can't exactly do so.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/illuminatedwax/pesterchum/issues/61#issuecomment-12131878.

**Comment by spacianMinecrafter** [comment]
Yes, I did. It's where the other files for Pesterchum are; in the Pesterchum folder in the C drive. It doesn't even open; all it does is show the circular loading button for about a second before disappearing completely.

**Comment by spacianMinecrafter** [comment]
All I do is click on the icon- nothing. I try running as administrator- still nothing.

**Comment by spacianMinecrafter** [comment]
Okay, I got it to run. Now what it's saying is- 
"[Errno 10051] A socket operation was attempted to an unreachable network."

**Comment by illuminatedwax** [comment]
Do you have any firewalls set up? The default port it tries to use is 6667.
Can you reach irc.mindfang.org?

**Comment by spacianMinecrafter** [comment]
all it says is hi?

**Comment by spacianMinecrafter** [comment]
Now it's
[Errno 10060] A connection attempt failed because the connected part did not properly respond after a period of time, or the established connection failed because conn......(it cut off the rest of it)

**Comment by spacianMinecrafter** [comment]
I turned the firewall off.

**Comment by spacianMinecrafter** [comment]
http://pastebin.com/D0J5Fg4j
