### ISSUE TITLE
Pesterchum help?

### ISSUE THREAD

**Issue by ghost** [illuminatedwax/pesterchum#69]
A while back I had installed Pesterchum, everything working and no issues. Then I'm not sure what happened but it wouldn't open anymore? I tried uninstalling and reinstalling it, but it just failed to work. I dropped the issue and just didn't have Pesterchum whatsoever for a few months. Now I uninstalled it completely, tried installing it again, but it still won't open. I also downloaded the debugger and a window saying "Error loading Python DLL: python.26dll (error code 126)" popped up when I ran it. I've tried opening Pesterchum with python.26dll, but nothing happens. Help please?

**Comment by illuminatedwax** [comment]
Make sure you put the debugger in the same directory as Pesterchum is
installed in

**Comment by illuminatedwax** [comment]
It should be the same folder as pesterchum.exe is in. Usually, issues with
pc are caused by corrput profile files or by unicode characters in the
users directory.
