### ISSUE TITLE
Quirk Issue

### ISSUE THREAD

**Issue by Sylvanon** [illuminatedwax/pesterchum#8]
Alright, I was hoping that you could help me out with this.

I'm a fairly new pesterchum user, and as such, am still figuring out the whole business with quirks.  After a few of my quirks failed to do anything to the text, I decided to try Karkat's quirk,
 REGEXP: "(.)"
REPLACED WITH: "upper(\1)"
When I went to test this quirk, it crashed pesterchum rather than anything else.  When I logged back in, I found that I couldn't post anything, or pesterchum would crash.  Even after I removed the quirk in it's entirety, persterchum continued to crash until I deleted the chumhandle and re-made it.

I hope that there's a solution to this!

blueMagician

**Comment by Sylvanon** [comment]
Also, I'm running this on Windows 7 if that makes a difference.

**Comment by Sylvanon** [comment]
If the themes make a difference, I'm also using the zodiac theme, though it appears to affect all themes.

**Comment by Horusium** [comment]
There is a file that needs to be put in your Quirks folder. Here is the thread in which you can obtain said file: http://www.mspaforums.com/showthread.php?37333-PESTERCHUM-3.14.1-New-Pesterchum-%286-26-3.41-8eta-pg54%29&p=5268166#post5268166

Hope it helps~

**Comment by Sylvanon** [comment]
:D  Yep! that appears to have fixed it!  Thanks much sah!
